services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: secret-santa-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secret-santa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: secret-santa-server
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${SERVER_PORT:-3000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - secret-santa-network
    volumes:
      - ./apps/server:/usr/src/app/apps/server
      - /usr/src/app/apps/server/node_modules
      - ./apps/server/src/prisma:/usr/src/app/src/prisma
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Secret Santa Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: secret-santa-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - secret-santa-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: secret-santa-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client
    networks:
      - secret-santa-network

volumes:
  postgres_data:
  postgres_test_data:

networks:
  secret-santa-network:
    driver: bridge
